### ISSUE TITLE
Error: No session id returned in login. 

### ISSUE THREAD

**Issue by Hans-Solo-Dolo** [Hyundai-Kia-Connect/kia_uvo#1052]
USA KIA EV9

**Version of the integration**
2.36.0

**Describe the bug**
Error: Failed setup, will retry: Config Not Ready: hyundai_kia_connect_api - No session id returned in login. Response: {"status":{"statusCode":1,"errorType":3,"errorCode":9789,"errorMessage":"Invalid Request"}}

File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 645, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: list object has no element 1
2025-03-05 08:52:26.967 ERROR (A1-Chamber-146) [custom_components.bambu_lab.pybambu] Chamber image connection rejected by the printer. Check provided access code and IP address.
2025-03-05 08:52:53.252 DEBUG (SyncWorker_7) [hyundai_kia_connect_api.KiaUvoApiUSA] hyundai_kia_connect_api - Sign In Response {"status":{"statusCode":1,"errorType":3,"errorCode":9789,"errorMessage":"Invalid Request"}}
2025-03-05 08:52:53.254 ERROR (MainThread) [custom_components.kia_uvo.coordinator] Unexpected error fetching kia_uvo data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()

Worked last night, woke up to error. Maybe need to refresh login token? Not sure how to do that without deleting the integration and re-adding which i would prefer not to do since I have several template sensors and automations with renamed entities.

**Comment by npike** [comment]
Same deal this morning for my Kia niro phev

**Comment by richie510** [comment]
I'm getting the same thing. The Kia/Hundai App/platform was under maintenance yesterday evening for me. I'm wondering if they changed something fundamental in the API?

**Comment by d4v3d** [comment]
I'm seeing the same error - came here to look for other reports.

**Comment by cdnninja** [comment]
Does the native app work?

**Comment by Hans-Solo-Dolo** [comment]
> Does the native app work?

Yes, native app works

**Comment by Hans-Solo-Dolo** [comment]
Out of curiosity, I tried the [other integration ](https://github.com/dahlb/ha_kia_hyundai) and it loaded fine.

**Comment by yorb** [comment]
Same with my Kia EV6 (USA). I tried reloading and enabling debug logging, nothing else aside from the "No session id returned" error reported above.

**Comment by Triple-S** [comment]
I just looked through the debug log and noticed that the LoginForm request returns an HTML page with error code 503 Service Temporarily Unavailable, so it might be just a maintenance downtime and no API change.

**Comment by joneselliot** [comment]
Same behavior here with EV6 in USA. Kia app login works as expected.

**Comment by daubman** [comment]
This started happening to me after updating to the just released HA Core 2025.3.0 version, but it looks like that must be a coincidence given the earlier reports here - including my log in case it helps at all:
```
Logger: custom_components.kia_uvo.coordinator
Source: helpers/update_coordinator.py:380
integration: Hyundai / Kia Connect ([documentation](https://github.com/Hyundai-Kia-Connect/kia_uvo), [issues](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues))
First occurred: 3:05:42 PM (14 occurrences)
Last logged: 3:17:46 PM

Unexpected error fetching kia_uvo data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/coordinator.py", line 107, in _async_update_data
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 169, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
        self.vehicle_manager.check_and_refresh_token
    )
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 136, in check_and_refresh_token
    self.initialize()
    ~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 75, in initialize
    self.token: Token = self.api.login(self.username, self.password)
                        ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiUSA.py", line 201, in login
    raise Exception(
        f"{DOMAIN} - No session id returned in login. Response: {response.text} headers {response.headers} cookies {response.cookies}"  # noqa
    )
Exception: hyundai_kia_connect_api - No session id returned in login. Response: 
{"status":{"statusCode":1,"errorType":3,"errorCode":9789,"errorMessage":"Invalid Request"}} 
headers {'Date': 'Wed, 05 Mar 2025 20:05:42 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'xid': 'a9124fab-6f5f-428d-a160-6ab008f98405', 'cf-cache-status': 'DYNAMIC', 'Set-
Cookie': '__cf_bm=[redacted]; path=/; expires=Wed, 05-Mar-25 20:35:42 GMT; domain=.api.owners.kia.com; HttpOnly; Secure; SameSite=None', 'Server': 'cloudflare', 'CF-RAY': '91bc3ac9ec0a4d0c-BOS', 'Content-Encoding': 'gzip'}
 cookies <RequestsCookieJar[<Cookie __cf_bm=[redacted]/>]>
```

**Comment by MarcusTaz** [comment]
Failed setup, will retry: Config Not Ready: hyundai_kia_connect_api - No session id returned in login. Response: {"status":{"statusCode":1,"errorType":3,"errorCode":9789,"errorMessage":"Invalid Request"}} headers {'Date': 'Thu, 06 Mar 2025 01:30:53 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'xid': '43ca74f4-6118-43c9-b620-1da1d837d7f4', 'cf-cache-status': 'DYNAMIC', 'Set-Cookie':

**Comment by chasebolt** [comment]
Experiencing same issue with my 24' Kia Sportage in the US.

**Comment by ianwood** [comment]
EV6. US. Same issue.

**Comment by fusionneo** [comment]
Good news: the fix is relatively simple. The headers just need to be updated to reflect the current app version. I submitted a pull request for the underlying API, so once that's pushed it should fix the issues with Home Assistant.

**Comment by MarcusTaz** [comment]
> Good news: the fix is relatively simple. The headers just need to be updated to reflect the current app version. I submitted a pull request for the underlying API, so once that's pushed it should fix the issues with Home Assistant.

any idea on how long this might take?

**Comment by fusionneo** [comment]
> > Good news: the fix is relatively simple. The headers just need to be updated to reflect the current app version. I submitted a pull request for the underlying API, so once that's pushed it should fix the issues with Home Assistant.
> 
> any idea on how long this might take?

That’s up to the project maintainers/people in charge.

**Comment by Hans-Solo-Dolo** [comment]
I see it was merged in the underlying api however I’m still seeing the same issue. Do we need to delete and reconfigure the integration or is there an update needed on this codebase as well?

**Comment by cdnninja** [comment]
Just need to update via HACS.

**Comment by MarcusTaz** [comment]
Working here as well, thank you Devs for the speedy fix, much appreciated!!!!

**Comment by Hans-Solo-Dolo** [comment]
@cdnninja is the “last_updated_at” entity last time the integration updated from the cloud or when the car updated to the cloud?

**Comment by Hans-Solo-Dolo** [comment]
I’m not sure why but it is being updated with the set interval that’s supposed to only pull from the servers, not the car. So every 15 minutes.

**Comment by cdnninja** [comment]
@Hans-Solo-Dolo  that topic also came up here: https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1050

Let's use that thread.  I'll close this one.
