### ISSUE TITLE
Kia Connect fails at login

### ISSUE THREAD

**Issue by Nislund** [Hyundai-Kia-Connect/kia_uvo#1309]
This error originated from a custom integration.

Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:148
integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 15:56:23 (3 occurrences)
Last logged: 19:27:01

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 148, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 92, in validate_input
    token: Token = await hass.async_add_executor_job(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        api.login, user_input[CONF_USERNAME], user_input[CONF_PASSWORD]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 184, in login
    _, access_token, authorization_code, expires_in = self._get_access_token(
                                                      ~~~~~~~~~~~~~~~~~~~~~~^
        stamp, refresh_token
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1363, in _get_access_token
    token_type = response["token_type"]
                 ~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'token_type'

**Comment by Merwases** [comment]
Did you update today to newest Integration version already ?

**Comment by donoghdb** [comment]
I have just gotten the same error.

**Comment by Merwases** [comment]
https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1307#issuecomment-3302922776

**Comment by Nislund** [comment]
Yes, it is the latest version.

**Comment by walter-ve** [comment]
What username (or ID) and password did you use?  

- don't give them ;-).

**Comment by hephie** [comment]
same issue here with version v2.44.1. But i'm having this issue now for about 4-5 weeks.
I'm from Belgium and own a Kia EV6.

Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:148
integration: Hyundai / Kia Connect ([documentation](https://github.com/Hyundai-Kia-Connect/kia_uvo), [issues](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues))
First occurred: 10:54:33 AM (2 occurrences)
Last logged: 10:54:52 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 148, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 92, in validate_input
    token: Token = await hass.async_add_executor_job(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        api.login, user_input[CONF_USERNAME], user_input[CONF_PASSWORD]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 184, in login
    _, access_token, authorization_code, expires_in = self._get_access_token(
                                                      ~~~~~~~~~~~~~~~~~~~~~~^
        stamp, refresh_token
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1363, in _get_access_token
    token_type = response["token_type"]
                 ~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'token_type'

**Comment by walter-ve** [comment]
@all: Use the refresh Token as password on version 2.44.1.  To get the Refresh Token as described in the link below.    When you installed the version 2.44.1 'normally' it gave you the below link for extra info on how to login.  

https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/wiki/Kia-Europe-Login-Flow

I can confirm it works perfectly from Belgium.

**Comment by brandmail** [comment]
I get the refresh token, put it in the password field but get the same unexpected error.

I have uninstalled, installed again fresh, reboot entire system, etc

**Comment by hephie** [comment]
> [@ALL](https://github.com/ALL): Use the refresh Token as password on version 2.44.1. To get the Refresh Token as described in the link below. When you installed the version 2.44.1 'normally' it gave you the below link for extra info on how to login. [https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/wiki/Kia-Europe-Login-Flow](url)
> 
> I can confirm it works perfectly from Belgium.

i wanted to try this? but the link you are providing is not working ? "no results"?  @walter-ve 

Your link is forwarding me to https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/created_by/url
I've tried searching on the europe-login-flow, but did not find anything?

Last update: I found the correct link, hehe
https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/wiki/Kia-Europe-Login-Flow

haha, its the same one, but for some reason redirect is doing something wrong.
try to go via https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/wiki

**Comment by walter-ve** [comment]
> > [@ALL](https://github.com/ALL): Use the refresh Token as password on version 2.44.1. To get the Refresh Token as described in the link below. When you installed the version 2.44.1 'normally' it gave you the below link for extra info on how to login. [https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/wiki/Kia-Europe-Login-Flow](url)
> > I can confirm it works perfectly from Belgium.
> 
> i wanted to try this? but the link you are providing is not working ? "no results"? [@walter-ve](https://github.com/walter-ve)
> 
> Your link is forwarding me to https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/created_by/url I've tried searching on the europe-login-flow, but did not find anything?

Another attempt to share the link https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/wiki/Kia-Europe-Login-Flow

(Somehow the link-tag doesn't work correctly...).

**Comment by hephie** [comment]
finally have it working again! thanks @walter-ve 
had to do it on windows. here are some instructions for other people. who can add this to the wiki maybe?

Download Python for Windows & Install
(check Add Python.exe to PATH)
https://www.python.org/ftp/python/3.13.7/python-3.13.7-amd64.exe

Download this file (or copy/paste the contents) in GetKiaRefreshToken.py
https://gist.githubusercontent.com/fuatakgun/fa4ef1e1d48b8dca2d22133d4d028dc9/raw/fe95ed7c02913f6277878a100458be78b794603d/gistfile1.txt

Open a new command prompt and run the commands below
pip3 install selenium requests
py GetKiaRefreshToken.py

done!

- a browser with kia germany will open
- login (email, password, verify human)
- wait for browser redirect and automatic close
- token will be now be visible in the command prompt
- delete your existing kia hub in the HA Hyundai / Kia Connect addon
- Add hub using your email and the refresh token

fully done!

**Comment by Phil182** [comment]
Thanks a lot for sharing this solution and clear instructions 🙏
Everything worked perfectly on my side. Really appreciate the effort you put into documenting it – saved me a ton of time!

**Comment by brandmail** [comment]
Not working for me, I still get the same error during login and with the refresh token as password...

**Comment by AfRotaker** [comment]
Thank you, but I can only enter the first command into the command prompt. The second one always returns an error "no such file or directory"

**Comment by bjkluft** [comment]
@hephie thanks for the explanation, that realy helped!

**Comment by grunneger** [comment]
@hephie that did rhe trick! Thanks, finally got it working again.

**Comment by brandmail** [comment]
I checked the log and the log shows this> Yes I request a refresh token and put it in the password field. Reinstalled from hacs and reboot everything completely:

Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:148
integration: kia_uvo ([documentation](https://github.com/Hyundai-Kia-Connect/kia_uvo), [issues](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues))
First occurred: 18 September 2025 at 13:32:19 (11 occurrences)
Last logged: 02:53:36

Unexpected exception
Traceback (most recent call last):
  File "/config/hyundai_kia_connect_api/KiaUvoApiEU.py", line 183, in login
    authorization_code = self._get_authorization_code_with_redirect_url(
        username, password, cookies
    )
  File "/config/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1169, in _get_authorization_code_with_redirect_url
    code = parse_qs(parsed_redirect.query).get("code")[0]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 148, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 92, in validate_input
    token: Token = await hass.async_add_executor_job(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        api.login, user_input[CONF_USERNAME], user_input[CONF_PASSWORD]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/hyundai_kia_connect_api/KiaUvoApiEU.py", line 188, in login
    authorization_code = self._get_authorization_code_with_form(
        username, password, cookies
    )
  File "/config/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1232, in _get_authorization_code_with_form
    login_form_action_url = soup.find("form")["action"].replace("&amp;", "&")
                            ~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by StraponXG** [comment]
I had the same issue - I was using the long 'Access Token'. I tried again with the 'Refresh Token' (much shorter) and that worked fine for me

<img width="964" height="155" alt="Image" src="https://github.com/user-attachments/assets/00e44a60-303e-4418-b0a6-25835ab31f08" />

**Comment by deltait** [comment]
Hello all! I also got an error like @brandmail. Tried reinstalling the integration. Also tried obtaining the refresh token another time (got a different one the second time).

2025-09-18 13:14:41.567 ERROR (MainThread) [custom_components.kia_uvo.coordinator] Unexpected error fetching kia_uvo data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 392, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/coordinator.py", line 109, in _async_update_data
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 171, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
        self.vehicle_manager.check_and_refresh_token
    )
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 147, in check_and_refresh_token
    self.initialize()
    ~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 82, in initialize
    self.token: Token = self.api.login(self.username, self.password)
                        ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 184, in login
    _, access_token, authorization_code, expires_in = self._get_access_token(
                                                      ~~~~~~~~~~~~~~~~~~~~~~^
        stamp, refresh_token
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1363, in _get_access_token
    token_type = response["token_type"]
                 ~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'token_type'


Just to be clear: I tried my username and the refresh token as password (the short one). Also tried with and without the PIN.

**Comment by MichaelS1955** [comment]
> finally have it working again! thanks [@walter-ve](https://github.com/walter-ve) had to do it on windows. here are some instructions for other people. who can add this to the wiki maybe?
> 
> Download Python for Windows & Install (check Add Python.exe to PATH) https://www.python.org/ftp/python/3.13.7/python-3.13.7-amd64.exe
> 
> Download this file (or copy/paste the contents) in GetKiaRefreshToken.py https://gist.githubusercontent.com/fuatakgun/fa4ef1e1d48b8dca2d22133d4d028dc9/raw/fe95ed7c02913f6277878a100458be78b794603d/gistfile1.txt
> 
> Open a new command prompt and run the commands below pip3 install selenium requests py GetKiaRefreshToken.py
> 
> done!
> 
> * a browser with kia germany will open
> * login (email, password, verify human)
> * wait for browser redirect and automatic close
> * token will be now be visible in the command prompt
> * delete your existing kia hub in the HA Hyundai / Kia Connect addon
> * Add hub using your email and the refresh token
> 
> fully done!

Hi,
I need some more help.
I have installed python on my window system and i downloaded the file.
Where dio I have to open a new command prompt? 

<img width="958" height="249" alt="Image" src="https://github.com/user-attachments/assets/88b84cea-56d7-4f66-9ffe-e9d0ac713c39" />

This seems to be the wrong command prompt.
The windows command window is also the wrong command prompt, same error message

**Comment by grunneger** [comment]
Are you sure you checked the Add to Path when you installed python?
The command prompt is the 'normal' windows command prompt (not the Powershell).

<img width="699" height="206" alt="Image" src="https://github.com/user-attachments/assets/977425a7-3760-4f71-921d-7e5a6032d18f" />

**Comment by Martines-hun** [comment]
> Hello all! I also got an error like [@brandmail](https://github.com/brandmail). Tried reinstalling the integration. Also tried obtaining the refresh token another time (got a different one the second time).
> 
> 2025-09-18 13:14:41.567 ERROR (MainThread) [custom_components.kia_uvo.coordinator] Unexpected error fetching kia_uvo data Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 392, in _async_refresh self.data = await self._async_update_data() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/kia_uvo/coordinator.py", line 109, in _async_update_data await self.async_check_and_refresh_token() File "/config/custom_components/kia_uvo/coordinator.py", line 171, in async_check_and_refresh_token await self.hass.async_add_executor_job( self.vehicle_manager.check_and_refresh_token ) File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 147, in check_and_refresh_token self.initialize() ~~~~~~~~~~~~~~~^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 82, in initialize self.token: Token = self.api.login(self.username, self.password) ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 184, in login _, access_token, authorization_code, expires_in = self._get_access_token( ~~~~~~~~~~~~~~~~~~~~~~^ stamp, refresh_token ^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1363, in _get_access_token token_type = response["token_type"] ~~~~~~~~^^^^^^^^^^^^^^ KeyError: 'token_type'
> 
> Just to be clear: I tried my username and the refresh token as password (the short one). Also tried with and without the PIN.

Don't enter anything in PIN field, and use 'refresh token' as your password. That worked for me like a charm :)

**Comment by MichaelS1955** [comment]
> Are you sure you checked the Add to Path when you installed python? The command prompt is the 'normal' windows command prompt (not the Powershell).
> 
> <img alt="Image" width="699" height="206" src="https://private-user-images.githubusercontent.com/185827068/491894527-977425a7-3760-4f71-921d-7e5a6032d18f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTgzODQ5OTUsIm5iZiI6MTc1ODM4NDY5NSwicGF0aCI6Ii8xODU4MjcwNjgvNDkxODk0NTI3LTk3NzQyNWE3LTM3NjAtNGY3MS05MjFkLTdlNWE2MDMyZDE4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkyMFQxNjExMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjgyNTgzYjNiNWZkYjA3OTQwNjg1ODY4NTY4NWIxOTM2MTBhODRmMjcxZWEyYzAyNzE0NzBjNjc5MDdhNTIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._i6GvJ-AZlda2pAaB1T5ew0u-UgxeackjbBMUfIMlP4">

Hi,
this is my path

<img width="561" height="293" alt="Image" src="https://github.com/user-attachments/assets/1fcbd833-48d2-4e2a-a97c-676bc166931e" />
Do I have to run the command in the powershell?

**Comment by walter-ve** [comment]
No; in cmd.exe , not powershell.

**Comment by walter-ve** [comment]
The syntax error; i am going to guess a quote error; maybe somehow a copy and paste changed a quote... also wondering if the German environment on windows didnt break something....

**Comment by Nislund** [comment]
I get this:

C:\Users\nlund>py GetKiaRefreshToken.py
Traceback (most recent call last):
  File "C:\Users\nlund\GetKiaRefreshToken.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'

C:\Users\nlund>

**Comment by walter-ve** [comment]
Check for selenium problems herr and solutions: https://www.browserstack.com/guide/modulenotfounderror-selenium

Where could we direct 'users' to address such problems?

**Comment by Nislund** [comment]
Done! 😊

Wrong path to selenium.. 😬

Many thanks for the help..  👍😊

**Comment by MichaelS1955** [comment]
> No; in cmd.exe , not powershell.

Hi, 
I executed the code in the powershell as administrator. The code was executed and I logged me in in the browser. The code returned the access and refresh token. 
When I added in HACS the Kia integration I used my email address and the refresh token.
I loooks like everything is working fine.

**Comment by MichaelS1955** [comment]
> The syntax error; i am going to guess a quote error; maybe somehow a copy and paste changed a quote... also wondering if the German environment on windows didnt break something....

I use the german environment and had no problem

**Comment by Fchavou** [comment]
> finally have it working again! thanks [@walter-ve](https://github.com/walter-ve) had to do it on windows. here are some instructions for other people. who can add this to the wiki maybe?
> 
> Download Python for Windows & Install (check Add Python.exe to PATH) https://www.python.org/ftp/python/3.13.7/python-3.13.7-amd64.exe
> 
> Download this file (or copy/paste the contents) in GetKiaRefreshToken.py https://gist.githubusercontent.com/fuatakgun/fa4ef1e1d48b8dca2d22133d4d028dc9/raw/fe95ed7c02913f6277878a100458be78b794603d/gistfile1.txt
> 
> Open a new command prompt and run the commands below pip3 install selenium requests py GetKiaRefreshToken.py
> 
> done!
> 
**> * a browser with kia germany will open**
> * login (email, password, verify human)
> * wait for browser redirect and automatic close
> * token will be now be visible in the command prompt
> * delete your existing kia hub in the HA Hyundai / Kia Connect addon
> * Add hub using your email and the refresh token
> 
> fully done!


This highlighted step does not work for me. Installing everything before this step (python incl path tickbox, the .cmd prompts etc) worked with selenium and all other things installed, but then nothing new (e.g. no browser/website) starts up like mentioned in this step above...

I tried it on 2 laptops; 1 corporate & 1 private.

Please help..

**Comment by MichaelS1955** [comment]
Hi,I opened powershell as administrator and executed the steps without problems.Am 23.09.2025 12:35 schrieb Fchavou ***@***.***>:Fchavou left a comment (Hyundai-Kia-Connect/kia_uvo#1309)

finally have it working again! thanks @walter-ve had to do it on windows. here are some instructions for other people. who can add this to the wiki maybe?
Download Python for Windows & Install (check Add Python.exe to PATH) https://www.python.org/ftp/python/3.13.7/python-3.13.7-amd64.exe
Download this file (or copy/paste the contents) in GetKiaRefreshToken.py https://gist.githubusercontent.com/fuatakgun/fa4ef1e1d48b8dca2d22133d4d028dc9/raw/fe95ed7c02913f6277878a100458be78b794603d/gistfile1.txt
Open a new command prompt and run the commands below pip3 install selenium requests py GetKiaRefreshToken.py
done!

> * a browser with kia germany will open

login (email, password, verify human)wait for browser redirect and automatic closetoken will be now be visible in the command promptdelete your existing kia hub in the HA Hyundai / Kia Connect addonAdd hub using your email and the refresh token
fully done!

This highlighted step does not work for me. Installing everything before this step (python incl path tickbox, the .cmd prompts etc) worked with selenium and all other things installed, but then nothing new (e.g. no browser/website) starts up like mentioned in this step above...
I tried it on 2 laptops; 1 corporate & 1 private.
Please help..

**Comment by Fchavou** [comment]
never mind, i think I solved it through the powershell method (not hephie's method above) :)

**Comment by ThoreKystervicz** [comment]
as an absolutely beginner, it worked fine for me with Mac, sublime text and incredible python3.
You did a great job, guys.

Greetings from cologne

**Comment by walter-ve** [comment]
Is there information known on how long the key stays active?

**Comment by superkco** [comment]
It works for me, thanks

**Comment by mikebaileyz** [comment]
I need help!  
Where do I find the add Python.exe to path box? It just installs without asking anything
How do I create the "GetKiaRefreshToken.py" file and where do I put it?
I am confused if I should then run the commands from inside of Python for Windows or at a normal command prompt?
thanks, really want to get this back working again for me

**Comment by cdnninja** [comment]
Closing in favor of: https://github.com/Hyundai-Kia-Connect/kia_uvo/discussions/1285
