### ISSUE TITLE
Error when adding integration to HA

### ISSUE THREAD

**Issue by Maximus97** [Hyundai-Kia-Connect/kia_uvo#561]
Hello. I am not able to set up add the integration in HA. After entering my credentials and saving, it gets stuck at loading and eventually times out. Getting this in the logs

```
Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:63
Integration: Kia Uvo / Hyundai Bluelink ([documentation](https://github.com/fuatakgun/kia_uvo), [issues](https://github.com/fuatakgun/kia_uvo/issues))
First occurred: 19:29:56 (1 occurrences)
Last logged: 19:29:56

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 159, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 63, in validate_input
    token: Token = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 182, in login
    device_id = self._get_device_id(stamp)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 953, in _get_device_id
    device_id = response["resMsg"]["deviceId"]
TypeError: string indices must be integers
```

**Comment by cdnninja** [comment]
Looks like you are in the EU?  What version? And does your mobile app work?

**Comment by SebastiaanKlippert** [comment]
I have the same error. v2.5.0 and HASS 2023.1.1 It worked before but I was a few versions behind on your integration, but on 2022.12

**Comment by cdnninja** [comment]
Could you see if 2.4.1 is any different?

**Comment by cdnninja** [comment]
Debug logs would help too.

**Comment by noltondyer** [comment]
It’s happening with me as well, even under 2.4.1 as well… here’s some debug logs:

`This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/kia_uvo/config_flow.py:166 
Integration: Hyundai / Kia Connect (documentation, issues) 
First occurred: 6:50:18 PM (3 occurrences) 
Last logged: 6:52:42 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 286, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 374, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 166, in async_step_user
    if self._reauth_entry is False:
AttributeError: 'ConfigFlow' object has no attribute '_reauth_entry'`

**Comment by noltondyer** [comment]
Update: same “Unknown error occurred” under 2.4.0 - same log thread as well.

**Comment by cdnninja** [comment]
Which version were those logs from?

**Comment by noltondyer** [comment]
Oh interesting. You would be correct. Didn’t even notice 🥴

those logs are from 2.5.0.

**Comment by noltondyer** [comment]
> Which version were those logs from? That's a different error than OP. I do see that mistake for _reauth. Working on a fix now.

If there’s anything I can do to help, shoot me a message on Discord! Thanks for your dedication. 💪

**Comment by cdnninja** [comment]
As a note @noltondyer  issue is fixed in 2.5.2. Anyone having the OPs issue please post debug logs and also be on the latest version. Last person that had that error a few days ago had issues with the native app at the same time.

**Comment by SebastiaanKlippert** [comment]
Sorry for just leaving a "same error here" reply without any logs, it was late 😐 
It was the error ending with "TypeError: string indices must be integers" which always occurred at HASS boot.  I still don't have any logs because I first upgraded to 2.5.2 and it seems to work now. I just did a reboot at it also starts correctly now.
So as far as I am concerned it is solved, thanks a lot.

**Comment by cdnninja** [comment]
@Maximus97 is this working for you as well? 

I didn't make changes related to your error but that happens when the api doesn't respond as we expect.

**Comment by cdnninja** [comment]
Closing due to lack of reply.

**Comment by Maximus97** [comment]
@cdnninja Yes, updating to 2.5.2 seems to have resolved it for me.

**Comment by Maximus97** [comment]
@cdnninja Yes, updating to 2.5.2 seems to have solved it for me.
